### ISSUE TITLE
Friendship flow is broken

### ISSUE THREAD

**Issue by smithshelke** [yslaa/SpotMoNa-API#1]
@yslaa  Please accept apology and fix it ASAP :(

**Comment by smithshelke** [comment]
?? Please fix asap

**Comment by smithshelke** [comment]
Any updates ?

**Comment by yslaa** [comment]
heey i just saw your email. I'm sorry because I've been gone for a very
long time and  remember I don't have a cell phone right? well my laptop was
reseted and all the access that i have to tg was gone. im sorry btw hii.
and im also busyyy lolllll hahahhaha

**Comment by smithshelke** [comment]
😭😭😭😭😭😭😭😭😭😭 
Finalllyyyyyy!!!!!!!!

Lets connect on facebook? I downloaded it today

**Comment by yslaa** [comment]
im sorry i dont use facebook anymore since i forgot my password hahaha and
the email that my mother used to create it is not working anymore since its
yandex i think

**Comment by smithshelke** [comment]
Hmm
